# Generated by Django 6.0.7 on 2026-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobil',
            name='markasi',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='modeli',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='yoqilgi_turi',
            field=models.CharField(max_length=20),
        ),
    ]
