# Generated by Django 6.0.7 on 2026-08-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_avtomobil_markasi_alter_avtomobil_modeli_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IshlabChiqaruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('davlat', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='avtomobil',
            name='ishlab_chiqaruvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avtomobillar', to='core.ishlabchiqaruvchi'),
        ),
    ]
