# Generated by Django 6.0.7 on 2026-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ishlabchiqaruvchi_avtomobil_ishlab_chiqaruvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobil',
            name='yaratuvchi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
