# Generated by Django 6.0.7 on 2026-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_avtomobil_yaratuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobil',
            name='oxirgi_tahrirlagan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
