# Generated by Django 6.0.7 on 2026-08-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_avtomobil_oxirgi_tahrirlagan'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobil',
            name='kod',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
